# Generated by Django 4.2.29 on 2026-05-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('type_carburant', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Électrique', 'Électrique'), ('Hybride', 'Hybride')], default='Diesel', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('kilometrage', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('En service', 'En service'), ('En réparation', 'En réparation'), ("Hors d'usage", "Hors d'usage")], default='En service', max_length=50)),
                ('date_fabrication', models.DateField()),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotte.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(max_length=200)),
                ('date_derniere_revision', models.DateField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotte.vehicule')),
            ],
        ),
    ]
